services:
  streamlit-app:
    container_name: streamlit-app
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/home/app
    environment:
      ENV_NAME: ${ENV_NAME}
    networks:
      - mainnetwork
    command: ["streamlit", "run", "main.py", "--server.address", "0.0.0.0", "--server.port", "8501"]


networks:
  mainnetwork:
    name: mainnetwork
volumes:
  stored-data: